Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [17]:
import numpy as np

def gen_vander_matrix(inputvector, N, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(N-i-1) for x in inputvector for i in range(N)]).reshape(inputvector.size,N)
    elif increasing:
        output_matrix = np.array([x**i for x in inputvector for i in range(N)]).reshape(inputvector.size,N)
    
    return output_matrix

print("------------Alexandre- Theophile Vandermonde Matrix-------------\n")
inputvector = np.array([1,2,4,6,8,10])
no_col_output_matrix  = 5
output_matrix_dec_order = gen_vander_matrix(inputvector,no_col_output_matrix,False)
output_matrix_inc_order = gen_vander_matrix(inputvector,no_col_output_matrix,True)
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_output_matrix,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_matrix_inc_order,"\n")


------------Alexandre- Theophile Vandermonde Matrix-------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



In [18]:
# using numpy.vander built-in function
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
output_matrix=np.vander(x)
print("Vander matrix of the input array :\n\n",output_matrix,"\n")
output_matrix=np.vander(x, increasing=True)
print("Vander matrix of the input array in increasing order:\n\n",output_matrix,"\n")

Vander matrix of the input array :

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]] 



Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [30]:
def moving_average(seqlist_n, k):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(seqlist_n, 1):
        cumsum.append(cumsum[i-1] + x) # summing up all the values one by one and appending to the list
        if i>=k:
            moving_ave = round(((cumsum[i] - cumsum[i-k])/k),2) #computing the moving average using temp array sum array cumsum
          
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving average dequence values list: ", moving_aves)
    print("Length of the list n-k+1: ", len(moving_aves))

In [31]:
seqlist_n = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

moving_average(seqlist_n,k)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list n-k+1:  11


In [32]:
seqlist_n = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
k = 4

moving_average(seqlist_n,k)

Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list n-k+1:  7


In [90]:
def moving_average(seqlist_n, k) :
    ret = np.cumsum(seqlist_n, dtype=float)
    ret[k:] = ret[k:] - ret[:-k]
    return ret[k - 1:] / k

seqlist_n = np.arange(20)
    
x=list(moving_average(seqlist_n,k=3))

print("Moving average sequence values list: ", x)
print("Length of the list n-k+1: ", len(x))


Moving average sequence values list:  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0]
Length of the list n-k+1:  18


In [92]:
x=list(moving_average(seqlist_n,k=4))

print("Moving average sequence values list: ", x)
print("Length of the list n-k+1: ", len(x))

Moving average sequence values list:  [1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5]
Length of the list n-k+1:  17
