Write a function to compute 5/0 and use try/except to catch the exceptions.

In [10]:
def Compute(x, y): 
    try: 
        result = x/y 
        print("Computation Success :", result) 
    except ZeroDivisionError: 
        print("Computation failed -->Arithmatic exception ") 

Compute(5,0) 

Computation failed -->Arithmatic exception 


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [14]:
subjects=["Americans", "Indians"]
verbs=["Play", "watch"]
objects=["Baseball","cricket"]

sentences_list = [(subj+" "+ vrb + " " + obj) for subj in subjects for vrb in verbs for obj in objects]
for sentences in sentences_list:
 print (sentences)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 2:
-----------
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [9]:
import numpy as np

def gen_vander_matrix(inputvector, N, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(N-i-1) for x in inputvector for i in range(N)]).reshape(inputvector.size,N)
    elif increasing:
        output_matrix = np.array([x**i for x in inputvector for i in range(N)]).reshape(inputvector.size,N)
    
    return output_matrix

print("------------Alexandre- Theophile Vandermonde Matrix-------------\n")
inputvector = np.array([1,2,4,6,8,10])
no_col_output_matrix  = 5
output_matrix_dec_order = gen_vander_matrix(inputvector,no_col_output_matrix,False)
output_matrix_inc_order = gen_vander_matrix(inputvector,no_col_output_matrix,True)
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_output_matrix,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_matrix_inc_order,"\n")


------------Alexandre- Theophile Vandermonde Matrix-------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



In [19]:
# using numpy.vander built-in function
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
output_matrix=np.vander(x)
print("Vander matrix of the input array :\n\n",output_matrix,"\n")
output_matrix=np.vander(x, increasing=True)
print("Vander matrix of the input array in increasing order:\n\n",output_matrix,"\n")


Vander matrix of the input array :

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]] 

